version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbtest

  budget-tracker-server:
    build: ./backend
    container_name: budget-tracker-server
    ports:
      - '3000:3000'
    command: npm start
    volumes:
      - ./backend/:/app
      - ./backend/node_modules:/app/node_modules
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbtest
      ME_CONFIG_MONGODB_URL: mongodb://dbuser:dbtest@mongo:27017/
    depends_on:
      - mongo
