version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbtest
    networks:
      - app-network

  budget-tracker-server:
    build: ./backend
    container_name: budget-tracker-server
    ports:
      - '3000:3000'
    command: npm start
    volumes:
      - ./backend/:/app
      - /app/node_modules
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbtest
      ME_CONFIG_MONGODB_URL: mongodb://dbuser:dbtest@mongo:27017/
    depends_on:
      - mongo
    networks:
      - app-network

  budget-tracker-ui:
    build: ./frontend
    container_name: budget-tracker-ui
    ports:
      - '5030:5030'
    command: npm run dev
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    restart: always
    depends_on:
      - budget-tracker-server
    networks:
      - app-network
  
networks:
  app-network:
      driver: bridge
